name: Bishal
description: A learning App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+27

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^2.1.0
  path_provider: ^1.6.11
  flutter_tex: ^3.6.7+9
  flutter_lorem: ^2.0.0
  bloc: ^7.0.0
  characters: ^1.0.0
  collection: ^1.14.11
  dotted_border: ^1.0.3
  dynamic_theme: ^1.0.1
  equatable: ^2.0.0
  expandable: ^5.0.1
  extended_image: ^2.0.0
  flare_flutter: ^3.0.0
  flutter_bloc: ^7.0.0
  flutter_custom_clippers: ^1.1.0
  flutter_local_notifications: ^4.0.1+2
  fluttertoast: ^8.0.3
  http: ^0.12.0+2
  intl: ^0.17.0
  json_serializable: ^4.0.2
  line_icons: ^2.0.1
  package_info: ^2.0.0
  pedantic: ^1.8.0+1
  provider: ^5.0.0
  qr_flutter: ^3.2.0
  rxdart: ^0.26.0
  share: ^0.6.3+1
  shared_preferences: ^0.5.4+5
  smooth_star_rating: ^1.0.4+2
  timeago: ^3.0.2
  tuple: ^2.0.0
  url_launcher: ^6.0.3
  vibration: ^1.2.2
  webview_flutter: ^1.0.7
  snapfeed: ^0.1.0+1
  flutter_bugfender: ^1.0.0
  stack_trace: ^1.9.3
  flutter_markdown: ^0.5.2
  sqflite: ^2.0.0+3
  path:
dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  bloc_test: ^8.0.0
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/flare/
    - assets/
    - assets/formulas/

  fonts:
    - family: PTSans
      fonts:
        - asset: assets/PT_Sans/PTSans-Bold.ttf
          weight: 600
        - asset: assets/PT_Sans/PTSans-Regular.ttf
          weight: 400
        - asset: assets/PT_Sans/PTSans-Italic.ttf
          # weight: 500
        - asset: assets/PT_Sans/PTSans-BoldItalic.ttf
          # weight: 600