name: Bishal
description: A learning App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.2+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #  printing: ^3.5.0
  pdf: ^1.9.0
  path_provider: ^1.6.11
  esys_flutter_share: ^1.0.2
  flutter_tex: ^3.6.7+8
  flutter_lorem: ^1.1.0
  redux: ^3.0.0
  flutter_redux: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/flag.png
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
